services:
  backend:
    image: jyotiprakashb23/khaopio-backend:latest
    ports:
      - "5000:5000"
    env_file: ./backend/.env
    restart: unless-stopped

  frontend:
    image: jyotiprakashb23/khaopio-frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
